# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeafa2fb01e53f5fc67353b8288a758f0eccede7b336a6dcc1714306dac854752cdb1c56811447538973a1a058ea636591320da49b647c1030f4b31c686b9219

test:
  secret_key_base: f2df207d080ae2232e3b69313edf8af22fe1754ece810ca1a594482f6b300ad1411e3983547666f30aa4289d2852b27c5b84ea4d7c203440c599b860377bec45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
